[linear-ridge-cholesky]使用 SPU 实现线性回归模型
secretflow/spu pull request #297
Opened 2023-08-10 12:05 UTC by magic-hya

### What problem does this PR solve?

Issue Number: Fixed #274

使用cholesky分解法实现ridge，在spu镜像中完成emul和test单元测试
### Possible side effects?
- Performance:
在diabetes数据集上，与sklearn的误差在0.01-0.02之间
- Backward compatibility:

2023-08-10 12:31 UTC, Candicepan commented
辛苦按照上方提示签订 CLA 哈

2023-08-10 12:34 UTC, tpppppub requested changes
Hi，除了 sml/linear_model 下的改动，.vscode 和 examples 下的请不要 commit

2023-08-11 02:08 UTC, magic-hya commented
> Hi，除了 sml/linear_model 下的改动，.vscode 和 examples 下的请不要 commit

好的

2023-08-11 06:18 UTC, magic-hya commented
recheck

2023-08-11 06:33 UTC, magic-hya commented
> I have read the CLA Document and I hereby sign the CLA

I have read the CLA Document and I hereby sign the CLA

2023-08-11 06:39 UTC, anakinxc commented
recheck

2023-08-11 06:43 UTC, anakinxc commented
Hi @magic-hya 

Please use [buildifier](https://github.com/bazelbuild/buildtools) to format bazel files.

Thanks

2023-08-11 07:19 UTC, deadlywing reviewed
另外，sml对目录结构做了一次重构，麻烦您按照现在的目录结构有序放置文件，并修改对应的BUILD.bazel文件

感谢支持～

2023-08-11 07:19 UTC, deadlywing commented on sml/linear_model/ridge_test.py
> +        print(result[:10])
单元测试需要比较明文sklearn的结果～

2023-08-11 07:19 UTC, deadlywing commented on sml/linear_model/ridge_emul.py
> +        print(result[:10])
麻烦比较一下明文sklearn的结果，并注明一下误差大小～

2023-08-11 07:19 UTC, deadlywing commented on sml/linear_model/ridge.py
> +    SVD = 'svd'  # not supported
当前utils的extmath.py中有svd的实现，但是在定点代数下发现比较容易溢出，如果您有兴趣可以调用里面的api实现

2023-08-11 07:19 UTC, deadlywing commented on sml/linear_model/ridge.py
> +        A = A.at[i, i].set(A[i][i] + alpha[0])
直接加一个对角阵即可，无需循环赋值～

2023-08-13 07:39 UTC, magic-hya commented
1.添加了fit_bias选项
2.优化了矩阵计算
3.格式化了bazel和py代码
4.增加了sklearn算法对比测试，误差在0.005以下
测试效果如下：
```
[sklearn_result]---------------------------------------------
[199.37653   73.73293  172.66196  161.55786  128.74493  103.354576
  83.321686 128.3768   160.04437  206.40292 ]
[spsim_result]-----------------------------------------------  
[199.3735    73.72925  172.65936  161.55386  128.74008  103.35206
  83.318665 128.37201  160.04198  206.40111 ]
[absolute_error]---------------------------------------------  
[0.00302124 0.003685   0.00259399 0.0039978  0.00485229 0.0025177
 0.00302124 0.00479126 0.00239563 0.0018158  0.00493622 0.00495148
 0.00419617 0.00210571 0.00326538 0.00457764 0.00273132 0.00369263
 0.00405884 0.00289154]
```

2023-08-14 06:52 UTC, deadlywing reviewed
另外，麻烦确保commit的代码已经：
使用black格式化过python代码，以及isort重排import语句

2023-08-14 06:52 UTC, deadlywing commented on sml/linear_model/ridge.py
> +from scipy import linalg, sparse
cleanup一下import语句

2023-08-14 06:52 UTC, deadlywing commented on sml/linear_model/ridge.py
> +        alpha = jnp.asarray(self.alpha, dtype=x.dtype).ravel()
似乎不必要转化为array？或许可以直接转化为float类型

2023-08-14 06:52 UTC, deadlywing commented on sml/linear_model/tests/ridge_test.py
> +    def test_simple(self):
测试函数名可以改为：test_ridge，明确一下测试函数的语意

2023-08-14 08:21 UTC, magic-hya commented
1.代码已使用black+isort格式化，请检查
2.alpha直接使用float类型，后续需要做多变量回归再做调整
3.测试函数名已修正
4.重新执行了测试用例，修改结果精度显示
测试效果如下：
```
Executing tests from //sml/linear_model/tests:ridge_test
-----------------------------------------------------------------------------
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
.
----------------------------------------------------------------------
Ran 1 test in 0.838s

OK
[sklearn_result]---------------------------------------------
[199.37653   73.73293  172.66196  161.55786  128.74493  103.354576
  83.321686 128.3768   160.04437  206.40292 ]
[spsim_result]-----------------------------------------------
[199.37305   73.728676 172.6597   161.5527   128.73994  103.349915
  83.31765  128.37166  160.04211  206.39943 ]
[absolute_error]---------------------------------------------
[0.00348 0.00426 0.00226 0.00516 0.00499 0.00466 0.00404 0.00514 0.00226
 0.00349 0.00556 0.00314 0.00468 0.00363 0.00404 0.0065  0.00435 0.00391
 0.0041  0.00439]
```

2023-08-14 08:39 UTC, deadlywing approved these changes
LGTM

2023-08-14 09:33 UTC, merged