add permute to python
secretflow/spu pull request #903
Opened 2024-11-05 12:53 UTC by cpz2024

# Pull Request

chenpinzhi
将底层permute提供给python报错

2024-11-06 04:52 UTC, deadlywing commented
```python
__all__ = ["permute"]

from functools import partial

from jax import core, dtypes
from jax.core import ShapedArray
from jax.interpreters import ad, batching, mlir, xla

# from jax.lib import xla_client
from jaxlib.hlo_helpers import custom_call


# Public facing interface
def permute(in1, in2):
    # Add necessary preprocessing code
    return _permute_prim.bind(in1, in2)


# *********************************
# *  SUPPORT FOR JIT COMPILATION  *
# *********************************


# For JIT compilation we need a function to evaluate the shape and dtype of the
# outputs of our op for some given inputs
def _permute_abstract(in1, in2):
    shape = in1.shape
    dtype = dtypes.canonicalize_dtype(in1.dtype)
    return ShapedArray(shape, dtype)


# We also need a lowering rule to provide an MLIR "lowering" of out primitive.
def _permute_lowering(ctx, in1, in2):
    # The inputs and outputs all have the same shape and memory layout
    # so let's predefine this specification
    dtype = mlir.ir.RankedTensorType(in1.type)
    shape = dtype.shape
    result_type = mlir.ir.RankedTensorType.get(shape, dtype.element_type)

    return custom_call(
        "permute",
        # Output types
        result_types=[result_type],
        # The inputs:
        operands=[in1, in2],
    ).results


# **********************************
# *  SUPPORT FOR FORWARD AUTODIFF  *
# **********************************


def _permute_jvp(args, tangents):
    raise NotImplementedError()


# ************************************
# *  SUPPORT FOR BATCHING WITH VMAP  *
# ************************************


# Our op already supports arbitrary dimensions so the batching rule is quite
# simple. The jax.lax.linalg module includes some example of more complicated
# batching rules if you need such a thing.
def _permute_batch(args, axes):
    raise NotImplementedError()


# *********************************************
# *  BOILERPLATE TO REGISTER THE OP WITH JAX  *
# *********************************************
_permute_prim = core.Primitive("permute")
# Change this to True if there are more than 1 output
_permute_prim.multiple_results = False
_permute_prim.def_impl(partial(xla.apply_primitive, _permute_prim))
_permute_prim.def_abstract_eval(_permute_abstract)

mlir.register_lowering(_permute_prim, _permute_lowering)

# Connect the JVP and batching rules
ad.primitive_jvps[_permute_prim] = _permute_jvp
batching.primitive_batchers[_permute_prim] = _permute_batch

```

我这边jax版本：
![image](https://github.com/user-attachments/assets/f3366f7b-83f6-4429-bf22-501255411c25)

修改一下`permute_impl.py`，应该就可以了。

2024-11-06 04:53 UTC, deadlywing commented
如果你的版本不和我一样，，可以根据具体的报错去检查一下api，jax里一些low level的api不是很稳定。

2024-11-06 04:59 UTC, deadlywing commented
另外，，permute其实也可以只用sort去实现，e.g. 
```python
# want to get  [13,12,11,10]
x = np.array([10, 11, 12, 13])  # data vector
y = np.array([3, 2, 1, 0])  # permutation
z = jax.lax.sort(operand=(y, x), dimension=-1, num_keys=1)[1]
print(f"permuted out = {z}")  # got [13 12 11 10]
```

`permute`对某些protocol可能跑不了，但是sort对所有protocol都支持。

2024-11-11 01:59 UTC, tpppppub requested changes

2024-11-11 01:59 UTC, tpppppub commented on sml/manifold/BUILD.bazel
> +# Copyright 2023 Ant Group Co., Ltd.
2024

2024-11-11 01:59 UTC, tpppppub commented on sml/manifold/MDS.py
> +import jax
A license header needed here

2024-11-11 01:59 UTC, tpppppub commented on sml/manifold/MDS.py
> +    # 全部求和
please use English for consistency

2024-11-11 02:16 UTC, closed without merging